name: reviewdog
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  languagetool:
    name: runner / languagetool
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: reviewdog/action-languagetool@v1
        with:
          reporter: github-check
          level: info
          patterns: |
            content/posts/**/*.md

      - name: misspell
        uses: reviewdog/action-misspell@v1
        with:
          reporter: github-check
          github_token: ${{ secrets.github_token }}
          locale: "US"
